# This workflow will deploy the app to google compute engine

name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}
    - name: deploy
      env: 
        GCE_ZONE: us-east1-b
        GCE_INSTANCE: instance-1
      run: |
        gcloud compute scp --zone $GCE_ZONE * $GCE_INSTANCE:/opt/discord-bot
        gcloud compute ssh --zone $GCE_ZONE $GCE_INSTANCE --command="sudo supervisorctl restart discordbot"
