# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy

on:
  push:
    branches: [ actions ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}
    - name: deploy
      #- name: run
      env: 
        GCE_ZONE: us-east1-b
        GCE_INSTANCE: instance-1
      run: |
        gcloud compute scp --zone $GCE_ZONE * $GCE_INSTANCE:/opt/discord-bot
        gcloud compute ssh --zone $GCE_ZONE $GCE_INSTANCE --command="sudo supervisorctl restart discordbot"
